genome: /public/home/mowp/db/Arabidopsis_thaliana/dna/Arabidopsis_thaliana.TAIR10.dna.toplevel.fa
cds_bed: /public/home/mowp/test/nanopore_cdna/test/cds.sorted.bed
polya_data: /public/home/mowp/test/nanopore_cdna/notebook/fhh.polyacaller.ann.tsv
gff_file: /public/home/mowp/db/Arabidopsis_thaliana/gff3/Arabidopsis_thaliana.TAIR10.46.gff3
bed_file: /public/home/mowp/test/nanopore_cdna/supplementary_data/get_representative_gene_model/araport11.representative.gene_model.bed
first_exon_path: /public/home/mowp/test/nanopore_cdna/supplementary_data/get_representative_gene_model/representative_gene_first_exon.tsv